### ISSUE TITLE
Базовый фронтенд

### ISSUE THREAD

**Issue by Bavpnet** [Voyagio/voyagio#1]
Сделать верстку по тем страницам, которые есть в фигме. Не трогать подбор достопримечательностей, там будут изменения. + пока адаптив не делаем

Страница авторизации, не нужно добавлять много фонов в этом спринте.
- [ ] сделать ток вход по логину
- [ ] добавить одну страницу на бекграунд
- [ ] Остальной дизайн должен совпадать

Страница поиска, фильтрацию пока не добавляем, просто пока кнопка, которая ничего не делает.

- [ ] Поиск с картинкой на бекграунде
- [ ] Сущность достопримечательности

Ссылка на фотографии: https://drive.google.com/drive/folders/1YT1Wa74x84Vf7dt_9WTKduRdBrQoJaps?usp=sharing

**Comment by blinikar** [comment]
https://www.figma.com/file/YBXDFPRKVh2boamVJIcJp8/%D0%A1apstone?type=design&node-id=0%3A1&t=zLZVt9UsTBUgthgT-1
