### ISSUE TITLE
Сконфигурировать Docker

### ISSUE THREAD

**Issue by ekuziakov** [Voyagio/voyagio#15]
- [x] Dockerfile для бекенда
- [ ] Dockerfile для фронтенда
- [x] docker-compose для бекенда
- [ ] docker-compose для фронтенда

**Comment by blinikar** [comment]
Если будем арендовывать внешний сервер то тогда не вижу смысла для фронта делать Docker потому что мы тогда просто через Netlify захостим и все

**Comment by blinikar** [comment]
Если с твоей стороны все готово с докером в таком случае закрываем эту задачу

**Comment by blinikar** [comment]
Через переписку пока решили docker для фронта не юзать, повесим домен на нетлифай, если не выйдет заведем докер. Таска закрыта
